"""Pydantic schema definitions for typed material content blocks.
The LLM transcribes rasterized PDF pages into these structured blocks.
HTML/JS is never directly generated by the model.
"""
from __future__ import annotations

from typing import Literal, Union, Optional
from pydantic import BaseModel, Field


class EjercicioItem(BaseModel):
    id: str = ""
    pregunta: str
    tipo: str = "cerrada"  # 'cerrada' | 'abierta'
    opciones: list[str] = Field(default_factory=list)
    respuesta: str = ""  # Correct answer string for closed auto-grading, empty for open-ended
    explicacion: str = ""
    puntos: int = 1


class BloqueTituloSeccion(BaseModel):
    tipo: Literal["titulo_seccion"] = "titulo_seccion"
    texto: str
    subtitulo: str = ""


class BloquePeriodo(BaseModel):
    tipo: Literal["periodo"] = "periodo"
    texto: str


class BloqueSubtitulo(BaseModel):
    tipo: Literal["subtitulo"] = "subtitulo"
    texto: str


class BloqueParrafo(BaseModel):
    tipo: Literal["parrafo"] = "parrafo"
    texto: str


class BloqueCaja(BaseModel):
    tipo: Literal["caja"] = "caja"
    estilo: str = "azul"  # Supports any color name: 'azul', 'verde', 'naranja', 'rosa', 'gris', 'morado', 'rojo', 'destacado', etc.
    titulo: str = ""
    contenido: str = ""


class BloqueLista(BaseModel):
    tipo: Literal["lista"] = "lista"
    ordenada: bool = False
    items: list[str] = Field(default_factory=list)


class BloqueTablaDatos(BaseModel):
    tipo: Literal["tabla_datos"] = "tabla_datos"
    columnas: list[str] = Field(default_factory=list)
    filas: list[list[str]] = Field(default_factory=list)


class BloqueTablaGenerica(BaseModel):
    tipo: Literal["tabla_generica"] = "tabla_generica"
    filas: list[list[str]] = Field(default_factory=list)


class BloqueFigura(BaseModel):
    tipo: Literal["figura"] = "figura"
    imagen_base64: str = ""  # WebP base64 image extracted from PDF
    pie: str = ""
    ancho_pct: int = 80


class BloqueFlujo(BaseModel):
    tipo: Literal["flujo"] = "flujo"
    pasos: list[str] = Field(default_factory=list)


class BloqueEjercicioRelleno(BaseModel):
    tipo: Literal["ejercicio_relleno"] = "ejercicio_relleno"
    instrucciones: str = "Responde las siguientes preguntas:"
    items: list[EjercicioItem] = Field(default_factory=list)


class BloqueZonaTrabajo(BaseModel):
    tipo: Literal["zona_trabajo"] = "zona_trabajo"
    instrucciones: str = "Zona de trabajo para resolver ejercicios:"
    modo: str = "escritura_y_dibujo"
    lineas_guia: bool = True


Bloque = Union[
    BloqueTituloSeccion,
    BloquePeriodo,
    BloqueSubtitulo,
    BloqueParrafo,
    BloqueCaja,
    BloqueLista,
    BloqueTablaDatos,
    BloqueTablaGenerica,
    BloqueFigura,
    BloqueFlujo,
    BloqueEjercicioRelleno,
    BloqueZonaTrabajo,
]


class PaginaTranscrita(BaseModel):
    numero_pagina: int
    encabezado: str = ""
    bloques: list[Bloque] = Field(default_factory=list)


class MetadatosMaterial(BaseModel):
    titulo: str = "Material Educativo"
    materia: str = "General"
    grado: str = ""
    unidad: str = ""
    docente: str = ""
    periodo: str = ""
    total_paginas: int = 1
